pipeline {
    agent any
    tools{
        maven 'Maven3'
        jdk 'Java17'
    }
stages{
    stage('Checkout Code') {
        steps {
            git branch: 'main', url: 'https://github.com/rdhule2020/Opencart.git
        }
    }
    
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean install -DskipTests'
            }
        }
            
        stage('Run Automation Test') {
            steps {
               sh 'mvn test'
            }
        }
        stage('Publish Test Report') {
            steps {
               TestNG 'target/surefire-reports/*.xml'
            }
        }
    }

    post
    {
        always {
            archiveArtifacts artifacts: 'target-reports/*.xml''
            allowEmptyArchive: true
}
    }
}
